import { BaristaProfile, CoffeeShop, Meet } from './meetka.models';

function isoDate(offsetDays: number): string {
	const date = new Date();
	date.setDate(date.getDate() + offsetDays);
	return date.toISOString().slice(0, 10);
}

export const COFFEE_SHOPS: CoffeeShop[] = [
	{
		id: 'shop-lviv-croissant',
		name: 'Lviv Croissants',
		photos: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
		address: 'Khreshchatyk St 15, Kyiv',
		location: { lat: 50.4489, lng: 30.5238 },
		workingHours: 'Mon–Sun 08:00–21:00',
		phone: '+380 44 123 4567',
		description: 'A cozy corner known for fresh croissants and single-origin filter coffee, popular with the local tech crowd.',
		interestIds: ['tech', 'startups', 'books'],
		baristaIds: ['barista-oksana', 'barista-ivan'],
		menu: [
			{
				id: 'cat-coffee',
				name: 'Coffee',
				products: [
					{ id: 'p1', name: 'Espresso', description: 'Double shot, house blend', price: 65, available: true },
					{ id: 'p2', name: 'Flat White', description: 'Espresso with steamed milk', price: 85, options: [{ label: 'Oat milk', price: 15 }], available: true },
					{ id: 'p3', name: 'Filter Coffee', description: 'Rotating single-origin', price: 90, available: true },
				],
			},
			{
				id: 'cat-pastry',
				name: 'Pastry',
				products: [
					{ id: 'p4', name: 'Butter Croissant', description: 'Baked fresh every morning', price: 55, available: true },
					{ id: 'p5', name: 'Almond Croissant', description: 'Filled with almond cream', price: 70, available: false },
				],
			},
		],
	},
	{
		id: 'shop-podil-roasters',
		name: 'Podil Roasters',
		photos: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
		address: 'Kontraktova Sq 4, Kyiv',
		location: { lat: 50.4643, lng: 30.5169 },
		workingHours: 'Mon–Fri 07:30–20:00, Sat–Sun 09:00–20:00',
		phone: '+380 44 234 5678',
		description: 'In-house roastery with a big communal table, a magnet for designers and creatives.',
		interestIds: ['design', 'art', 'photography'],
		baristaIds: ['barista-marta'],
		menu: [
			{
				id: 'cat-coffee',
				name: 'Coffee',
				products: [
					{ id: 'p1', name: 'Cappuccino', description: 'Classic Italian style', price: 75, available: true },
					{ id: 'p2', name: 'Cold Brew', description: '18-hour steeped', price: 95, available: true },
				],
			},
		],
	},
	{
		id: 'shop-print-station',
		name: 'Print Station Coffee',
		photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
		address: 'Antonovycha St 20, Kyiv',
		location: { lat: 50.4276, lng: 30.5194 },
		workingHours: 'Mon–Sun 08:00–22:00',
		phone: '+380 44 345 6789',
		description: 'Former print house turned coffee shop, hosts language exchange evenings every week.',
		interestIds: ['languages', 'networking', 'books'],
		baristaIds: ['barista-ivan'],
		menu: [
			{
				id: 'cat-coffee',
				name: 'Coffee',
				products: [
					{ id: 'p1', name: 'Americano', description: 'Espresso with hot water', price: 60, available: true },
					{ id: 'p2', name: 'Latte', description: 'Espresso with steamed milk', price: 80, options: [{ label: 'Extra shot', price: 20 }], available: true },
				],
			},
			{
				id: 'cat-tea',
				name: 'Tea',
				products: [{ id: 'p3', name: 'Herbal Tea', description: 'Rotating seasonal blend', price: 55, available: true }],
			},
		],
	},
	{
		id: 'shop-run-club-cafe',
		name: 'Run Club Café',
		photos: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800'],
		address: 'Naberezhno-Khreshchatytska St 10, Kyiv',
		location: { lat: 50.4581, lng: 30.5145 },
		workingHours: 'Mon–Sun 06:30–19:00',
		phone: '+380 44 456 7890',
		description: 'Coffee shop by the river, meeting point for morning runners and wellness meets.',
		interestIds: ['sports', 'wellness'],
		baristaIds: ['barista-oksana'],
		menu: [
			{
				id: 'cat-coffee',
				name: 'Coffee',
				products: [{ id: 'p1', name: 'Espresso', description: 'Double shot', price: 60, available: true }],
			},
			{
				id: 'cat-smoothie',
				name: 'Smoothies',
				products: [{ id: 'p2', name: 'Green Smoothie', description: 'Spinach, apple, ginger', price: 100, available: true }],
			},
		],
	},
	{
		id: 'shop-board-and-bean',
		name: 'Board & Bean',
		photos: ['https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800'],
		address: 'Velyka Vasylkivska St 55, Kyiv',
		location: { lat: 50.4312, lng: 30.5228 },
		workingHours: 'Mon–Sun 10:00–23:00',
		phone: '+380 44 567 8901',
		description: 'Board games, specialty coffee, and a monthly gaming meetup community.',
		interestIds: ['gaming', 'networking', 'food'],
		baristaIds: ['barista-marta', 'barista-ivan'],
		menu: [
			{
				id: 'cat-coffee',
				name: 'Coffee',
				products: [{ id: 'p1', name: 'Mocha', description: 'Espresso, chocolate, steamed milk', price: 90, available: true }],
			},
		],
	},
];

export const BARISTA_PROFILES: BaristaProfile[] = [
	{
		id: 'barista-oksana',
		name: 'Oksana',
		photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
		coffeeShopId: 'shop-lviv-croissant',
		bio: 'Loves introducing regulars to each other over a shared love of filter coffee.',
		interestIds: ['tech', 'books', 'wellness'],
		available: true,
		tipLinks: [{ label: 'Monobank jar', url: 'https://send.monobank.ua/example' }],
		socialLinks: [{ label: 'Instagram', url: 'https://instagram.com/example' }],
	},
	{
		id: 'barista-ivan',
		name: 'Ivan',
		photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
		coffeeShopId: 'shop-print-station',
		bio: 'Runs the weekly language exchange evenings and knows every regular by name.',
		interestIds: ['languages', 'networking', 'gaming'],
		available: true,
		tipLinks: [],
		socialLinks: [{ label: 'Instagram', url: 'https://instagram.com/example' }],
	},
	{
		id: 'barista-marta',
		name: 'Marta',
		photo: 'https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?w=400',
		coffeeShopId: 'shop-podil-roasters',
		bio: 'Former graphic designer, now pulls shots and curates the shop art wall.',
		interestIds: ['design', 'art', 'photography'],
		available: false,
		tipLinks: [{ label: 'PayPal', url: 'https://paypal.me/example' }],
		socialLinks: [],
	},
];

export const MEETS: Meet[] = [
	{
		id: 'meet-frontend-coffee',
		title: 'Frontend Coffee Chat',
		description: 'Casual chat about frontend frameworks, Angular signals, and side projects.',
		interestIds: ['tech', 'startups'],
		coffeeShopId: 'shop-lviv-croissant',
		date: isoDate(2),
		startTime: '18:00',
		endTime: '19:30',
		visibility: 'public',
		organizerId: 'user-demo',
		organizerName: 'Denys',
		organizerThumb: 'default.png',
		participantLimit: 10,
		participants: [
			{ userId: 'user-demo', name: 'Denys', thumb: 'default.png', going: true },
			{ userId: 'user-2', name: 'Anna', thumb: 'default.png', going: true },
		],
		recurring: null,
		shareToken: 'tok-frontend-coffee',
		active: true,
	},
	{
		id: 'meet-design-crit',
		title: 'Design Critique Circle',
		description: 'Bring a work-in-progress and get friendly feedback from fellow designers.',
		interestIds: ['design', 'art'],
		coffeeShopId: 'shop-podil-roasters',
		date: isoDate(4),
		startTime: '17:00',
		endTime: '18:30',
		visibility: 'public',
		organizerId: 'user-3',
		organizerName: 'Marta K.',
		organizerThumb: 'default.png',
		participantLimit: 8,
		participants: [{ userId: 'user-3', name: 'Marta K.', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-design-crit',
		active: true,
	},
	{
		id: 'meet-language-exchange',
		title: 'English–Ukrainian Language Exchange',
		description: 'Practice conversational English and Ukrainian over coffee, all levels welcome.',
		interestIds: ['languages', 'networking'],
		coffeeShopId: 'shop-print-station',
		date: isoDate(1),
		startTime: '19:00',
		endTime: '20:30',
		visibility: 'public',
		organizerId: 'user-4',
		organizerName: 'Ivan P.',
		organizerThumb: 'default.png',
		participantLimit: null,
		participants: [
			{ userId: 'user-4', name: 'Ivan P.', thumb: 'default.png', going: true },
			{ userId: 'user-5', name: 'Sofia', thumb: 'default.png', going: true },
			{ userId: 'user-6', name: 'Tom', thumb: 'default.png', going: false },
		],
		recurring: { type: 'weekly', days: [3] },
		shareToken: 'tok-language-exchange',
		active: true,
	},
	{
		id: 'meet-morning-run',
		title: 'Morning Run + Coffee',
		description: 'Easy 5k along the river, followed by coffee and stretching.',
		interestIds: ['sports', 'wellness'],
		coffeeShopId: 'shop-run-club-cafe',
		date: isoDate(3),
		startTime: '07:00',
		endTime: '08:00',
		visibility: 'public',
		organizerId: 'user-7',
		organizerName: 'Oksana R.',
		organizerThumb: 'default.png',
		participantLimit: 15,
		participants: [{ userId: 'user-7', name: 'Oksana R.', thumb: 'default.png', going: true }],
		recurring: { type: 'weekly', days: [1, 3, 5] },
		shareToken: 'tok-morning-run',
		active: true,
	},
	{
		id: 'meet-board-games',
		title: 'Board Game Night',
		description: 'Monthly board game night, bring your favorite game or learn a new one.',
		interestIds: ['gaming', 'networking'],
		coffeeShopId: 'shop-board-and-bean',
		date: isoDate(6),
		startTime: '18:30',
		endTime: '21:30',
		visibility: 'public',
		organizerId: 'user-8',
		organizerName: 'Board & Bean Crew',
		organizerThumb: 'default.png',
		participantLimit: 20,
		participants: [],
		recurring: { type: 'monthly', days: [] },
		shareToken: 'tok-board-games',
		active: true,
	},
	{
		id: 'meet-founders-only',
		title: 'Founders-Only Coffee',
		description: 'Private catch-up for a small group of early-stage founders.',
		interestIds: ['startups', 'networking'],
		coffeeShopId: 'shop-lviv-croissant',
		date: isoDate(5),
		startTime: '09:00',
		endTime: '10:00',
		visibility: 'private',
		organizerId: 'user-demo',
		organizerName: 'Denys',
		organizerThumb: 'default.png',
		participantLimit: 4,
		participants: [{ userId: 'user-demo', name: 'Denys', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-founders-only',
		active: true,
	},
	{
		id: 'meet-past-photo-walk',
		title: 'Photo Walk: Podil Streets',
		description: 'Explored Podil backstreets with cameras, ended with cold brew.',
		interestIds: ['photography', 'art'],
		coffeeShopId: 'shop-podil-roasters',
		date: isoDate(-6),
		startTime: '16:00',
		endTime: '18:00',
		visibility: 'public',
		organizerId: 'user-9',
		organizerName: 'Marta K.',
		organizerThumb: 'default.png',
		participantLimit: 12,
		participants: [{ userId: 'user-9', name: 'Marta K.', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-photo-walk',
		active: true,
	},
];
