import { Meet } from './meet.interface';

function isoDate(offsetDays: number): string {
	const date = new Date();
	date.setDate(date.getDate() + offsetDays);
	return date.toISOString().slice(0, 10);
}

export const MEETS: Meet[] = [
	{
		id: 'meet-frontend-coffee',
		title: 'Frontend Coffee Chat',
		description: 'Casual chat about frontend frameworks, Angular signals, and side projects.',
		interestIds: ['tech', 'startups'],
		coffeeShopId: 'shop-lviv-croissant',
		date: isoDate(2),
		startTime: '18:00',
		endTime: '19:30',
		visibility: 'public',
		organizerId: 'user-demo',
		organizerName: 'Denys',
		organizerThumb: 'default.png',
		participantLimit: 10,
		participants: [
			{ userId: 'user-demo', name: 'Denys', thumb: 'default.png', going: true },
			{ userId: 'user-2', name: 'Anna', thumb: 'default.png', going: true },
		],
		recurring: null,
		shareToken: 'tok-frontend-coffee',
		active: true,
	},
	{
		id: 'meet-design-crit',
		title: 'Design Critique Circle',
		description: 'Bring a work-in-progress and get friendly feedback from fellow designers.',
		interestIds: ['design', 'art'],
		coffeeShopId: 'shop-podil-roasters',
		date: isoDate(4),
		startTime: '17:00',
		endTime: '18:30',
		visibility: 'public',
		organizerId: 'user-3',
		organizerName: 'Marta K.',
		organizerThumb: 'default.png',
		participantLimit: 8,
		participants: [{ userId: 'user-3', name: 'Marta K.', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-design-crit',
		active: true,
	},
	{
		id: 'meet-language-exchange',
		title: 'English–Ukrainian Language Exchange',
		description: 'Practice conversational English and Ukrainian over coffee, all levels welcome.',
		interestIds: ['languages', 'networking'],
		coffeeShopId: 'shop-print-station',
		date: isoDate(1),
		startTime: '19:00',
		endTime: '20:30',
		visibility: 'public',
		organizerId: 'user-4',
		organizerName: 'Ivan P.',
		organizerThumb: 'default.png',
		participantLimit: null,
		participants: [
			{ userId: 'user-4', name: 'Ivan P.', thumb: 'default.png', going: true },
			{ userId: 'user-5', name: 'Sofia', thumb: 'default.png', going: true },
			{ userId: 'user-6', name: 'Tom', thumb: 'default.png', going: false },
		],
		recurring: { type: 'weekly', days: [3] },
		shareToken: 'tok-language-exchange',
		active: true,
	},
	{
		id: 'meet-morning-run',
		title: 'Morning Run + Coffee',
		description: 'Easy 5k along the river, followed by coffee and stretching.',
		interestIds: ['sports', 'wellness'],
		coffeeShopId: 'shop-run-club-cafe',
		date: isoDate(3),
		startTime: '07:00',
		endTime: '08:00',
		visibility: 'public',
		organizerId: 'user-7',
		organizerName: 'Oksana R.',
		organizerThumb: 'default.png',
		participantLimit: 15,
		participants: [{ userId: 'user-7', name: 'Oksana R.', thumb: 'default.png', going: true }],
		recurring: { type: 'weekly', days: [1, 3, 5] },
		shareToken: 'tok-morning-run',
		active: true,
	},
	{
		id: 'meet-board-games',
		title: 'Board Game Night',
		description: 'Monthly board game night, bring your favorite game or learn a new one.',
		interestIds: ['gaming', 'networking'],
		coffeeShopId: 'shop-board-and-bean',
		date: isoDate(6),
		startTime: '18:30',
		endTime: '21:30',
		visibility: 'public',
		organizerId: 'user-8',
		organizerName: 'Board & Bean Crew',
		organizerThumb: 'default.png',
		participantLimit: 20,
		participants: [],
		recurring: { type: 'monthly', days: [] },
		shareToken: 'tok-board-games',
		active: true,
	},
	{
		id: 'meet-founders-only',
		title: 'Founders-Only Coffee',
		description: 'Private catch-up for a small group of early-stage founders.',
		interestIds: ['startups', 'networking'],
		coffeeShopId: 'shop-lviv-croissant',
		date: isoDate(5),
		startTime: '09:00',
		endTime: '10:00',
		visibility: 'private',
		organizerId: 'user-demo',
		organizerName: 'Denys',
		organizerThumb: 'default.png',
		participantLimit: 4,
		participants: [{ userId: 'user-demo', name: 'Denys', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-founders-only',
		active: true,
	},
	{
		id: 'meet-past-photo-walk',
		title: 'Photo Walk: Podil Streets',
		description: 'Explored Podil backstreets with cameras, ended with cold brew.',
		interestIds: ['photography', 'art'],
		coffeeShopId: 'shop-podil-roasters',
		date: isoDate(-6),
		startTime: '16:00',
		endTime: '18:00',
		visibility: 'public',
		organizerId: 'user-9',
		organizerName: 'Marta K.',
		organizerThumb: 'default.png',
		participantLimit: 12,
		participants: [{ userId: 'user-9', name: 'Marta K.', thumb: 'default.png', going: true }],
		recurring: null,
		shareToken: 'tok-photo-walk',
		active: true,
	},
];
